
apiVersion: apps/v1
kind: Deployment
metadata:
  name: our-server-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: our-server
  template:
    metadata:
      labels:
        app: our-server
    spec:
      containers:
      - name: our-server
        image: 192.168.153.130:5000/our-server:latest
        ports:
        - containerPort: 80
